version: '2.4'

services:
  osp-ejabberd:
    build: ./Ejabberd
    restart: unless-stopped

    cpus: 2.0
    mem_limit: 256m
    memswap_limit: 256m
    mem_reservation: 256m

    ports:
      - '5280:5280'
      - '4560:4560'
      - '5222:5222'
    environment:
      - EJABBERD_PASSWORD="changeme"
      - EJABBERD_DOMAIN="streams.example.com"
      - OSP_API_PROTOCOL="http"
      - OSP_API_DOMAIN="streams.example.com"
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.ejabberd.entrypoints=websecure"
    #  - "traefik.http.routers.ejabberd.rule=Host(`streams.example.com`) && PathPrefix(`/http-bind/`)"
    #  - "traefik.http.middlewares.bosh_url-regex.replacepathregex.regex=^/http-bind/(.*)"
    #  - "traefik.http.middlewares.bosh_url-regex.replacepathregex.replacement=/bosh/$$1"
    #  - "traefik.http.routers.ejabberd.middlewares=bosh_url-regex@docker"
    #  - "traefik.http.routers.ejabberd.tls.domains[0].main=streams.example.com"
    #  - "traefik.http.routers.ejabberd.tls.certresolver=le"
    #  - "traefik.http.services.ejabberd.loadbalancer.server.port=5280"
    volumes:
    - "/srv/docker/osp-app/data/ejabberd/database:/home/ejabberd/database"

  osp_core:
    build: ./OSP-Core
    restart: unless-stopped

    cpus: 2.0
    mem_limit: 2048m
    memswap_limit: 2304m
    mem_reservation: 2048m

    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.streamingapp.entrypoints=websecure"
    #  - "traefik.http.routers.streamingapp.rule=Host(`streams.example.com`)"
    #  - "traefik.http.routers.streamingapp.tls.domains[0].main=streams.example.com"
    #  - "traefik.http.routers.streamingapp.tls.certresolver=le"
    #  - "traefik.http.services.streamingapp.loadbalancer.server.port=80"
    ports:
      - '8088:80'
    environment:
      - OSP_SERVER_ADDRESS="streams.example.com"
      - REDIS_HOST=osp_redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - DB_URL="mysql+pymysql://osp:REPLACEME_osp_database_password_REPLACEME@osp_db/osp"
      - FLASK_SECRET="REPLACEME_osp_flask_secret_REPLACEME"
      - FLASK_SALT="REPLACEME_osp_flask_salt_REPLACEME"
      - OSP_ALLOWREGISTRATION=True
      - OSP_REQUIREVERIFICATION=False
      - EJABBERDPASS="CHANGEME"
      - EJABBERDSERVER=osp_ejabberd
      # - TZ=ETC/UTC
    volumes:
      - "/srv/docker/osp-app/data/www:/var/www"
      - "/srv/docker/osp-app/data/tmpfs/live:/var/www/live"
      - "/srv/docker/osp-app/data/tmpfs/live-adapt:/var/www/live-adapt"
      - "/srv/docker/osp-app/data/tmpfs/stream-thumb:/var/www/stream-thumb"
    depends_on:
      - osp_db
      - osp_redis
      - osp-ejabberd
    entrypoint: ["/opt/osp/setup/wait-for-it.sh", "osp_db:3306", "-t", "60", "--", "/opt/osp/setup/entrypoint.sh"]

  osp_rtmp:
    build: ./OSP-RTMP
    restart: unless-stopped

    cpus: 2.0
    mem_limit: 2048m
    memswap_limit: 2304m
    mem_reservation: 2048m

    ports:
      - '1935:1935'
    environment:
      - OSPCOREAPI="http://streams.example.com"
      - FLASK_SECRET="changeme"
    volumes:
      - "/srv/docker/osp-app/data/www:/var/www"
      - "/srv/docker/osp-app/data/tmpfs/live:/var/www/live"
      - "/srv/docker/osp-app/data/tmpfs/live-adapt:/var/www/live-adapt"
      - "/srv/docker/osp-app/data/tmpfs/stream-thumb:/var/www/stream-thumb"
    depends_on:
      - osp_core

  osp_db:
    image: mariadb
    restart: unless-stopped
    cpus: 2.0
    mem_limit: 256m
    memswap_limit: 512m
    mem_reservation: 256m
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /srv/docker/osp-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REPLACEME_osp_dbroot_password_REPLACEME
      - MYSQL_PASSWORD=REPLACEME_osp_database_password_REPLACEME
      - MYSQL_DATABASE=osp
      - MYSQL_USER=osp
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=REPLACEME_osp_dbroot_password_REPLACEME --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 1s
      retries: 5
      start_period: 30s

  osp_redis:
    image: redis
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 128m
    memswap_limit: 256m
    mem_reservation: 128m
